package net.davethemlgpro.client.datagen;

import net.davethemlgpro.client.translation.TranslationKey;

import java.util.Collections;
import java.util.EnumMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static java.util.Map.entry;
import static net.davethemlgpro.client.translation.TranslationKey.*;

public enum HudLanguage {
	EN(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "Open HUD Layout Editor"),
		entry(MODULE_ARMOR, "Armor HUD"),
		entry(MODULE_ITEM_PICKUP, "Item Pickup HUD"),
		entry(EDITOR_TITLE, "HUD Layout Editor"),
		entry(EDITOR_INSTRUCTIONS, "Drag to move. Hold Left Alt for grid snapping. Shift-click for quick settings."),
		entry(EDITOR_RESET, "Reset"),
		entry(EDITOR_SAVE_FAILED, "Changes could not be saved."),
		entry(EDITOR_VANILLA_HUD_AREA, "Vanilla HUD area"),
		entry(EDITOR_SETTINGS_OPEN, "Global settings"),
		entry(EDITOR_SETTINGS_TITLE, "Global Settings"),
		entry(EDITOR_SETTINGS_TAB_GENERAL, "General"),
		entry(EDITOR_SETTINGS_TAB_GRID, "Grid"),
		entry(EDITOR_SETTINGS_TAB_MODULES, "Modules"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED, "%s Enabled"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED_DESCRIPTION,
			"Turns %s on or off without changing its saved settings."),
		entry(EDITOR_SETTINGS_MODULE_RESET, "Reset %s"),
		entry(EDITOR_SETTINGS_MODULE_RESET_DESCRIPTION,
			"Restores this module's settings and layout to their defaults."),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL, "Reset All Modules"),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL_DESCRIPTION,
			"Restores every HUD module to its defaults without changing editor settings."),
		entry(EDITOR_SETTINGS_ACCENT_COLOR, "Accent Color"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR_DESCRIPTION,
			"Sets the accent color used by popovers, buttons, sliders, and other editor controls."),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR, "Module Border"),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR_DESCRIPTION,
			"Sets the default outline color around modules in the layout editor."),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR, "Module Highlight"),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR_DESCRIPTION,
			"Sets the outline color shown when a module is highlighted under the pointer."),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR, "Minor Grid"),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR_DESCRIPTION, "Sets the color of the five-pixel grid lines."),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR, "Major Grid"),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR_DESCRIPTION, "Sets the color of the twenty-pixel grid lines."),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR, "Center Guides"),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR_DESCRIPTION,
			"Sets the color of the horizontal and vertical center guides."),
		entry(POPOVER_NO_SETTINGS, "No quick settings available."),
		entry(SETTINGS_TAB_LAYOUT, "Layout"),
		entry(SETTINGS_TAB_BAR, "Bar"),
		entry(SETTINGS_TAB_TEXT, "Text"),
		entry(SETTINGS_SECTION_LAYOUT, "Layout"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Durability Bar"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Durability Text"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Low Durability Warning"),
		entry(SETTINGS_SECTION_COLORS, "Colors"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE, "Layout Mode"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE_DESCRIPTION,
			"Moves the Armor HUD as one group or lets each armor slot be positioned independently."),
		entry(SETTINGS_ARMOR_ORIENTATION, "Orientation"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION, "Arranges armor slots horizontally or vertically."),
		entry(SETTINGS_ARMOR_SCALE, "Scale"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Changes the size of the entire Armor HUD."),
		entry(SETTINGS_ARMOR_SPACING, "Slot Spacing"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Controls the space between armor slots."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Slot Style"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION, "Selects the background style used for armor slots."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Show Empty Slots"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION, "Shows slots even when no armor is equipped."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Center Visible Slots"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Centers equipped armor slots when empty slots are hidden."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Show Durability Bar"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Shows a durability bar for damageable armor."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Bar Height"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Controls the height of the durability bar."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Horizontal Padding"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Adds horizontal space inside the durability bar."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR, "Background"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR_DESCRIPTION,
			"Sets the durability bar background color."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR, "Healthy"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR_DESCRIPTION,
			"Sets the color used for high durability."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR, "Warning"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR_DESCRIPTION,
			"Sets the color used for medium durability."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR, "Critical"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR_DESCRIPTION,
			"Sets the color used for low durability."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Text Display"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Selects whether durability is hidden, a value, or a percentage."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Text Position"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Positions the durability text relative to each armor slot."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Text Scale"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Changes the size of the durability text."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Text Shadow"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Draws a shadow behind the durability text."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Color Text by Durability"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Uses healthy, warning, and critical colors for durability text."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR, "Text Color"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR_DESCRIPTION,
			"Sets the fixed durability text color."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR, "Healthy Text"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR_DESCRIPTION,
			"Sets the text color used for high durability."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR, "Warning Text"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR_DESCRIPTION,
			"Sets the text color used for medium durability."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR, "Critical Text"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR_DESCRIPTION,
			"Sets the text color used for low durability."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Show Low Durability Warning"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Highlights armor whose durability is at or below the threshold."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Warning Threshold"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Sets the durability percentage at which warnings begin."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Warning Style"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Selects how the low-durability warning is animated."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR, "Warning Color"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR_DESCRIPTION,
			"Sets the low-durability highlight color."),
		entry(SETTINGS_ITEM_PICKUP_TAB_GENERAL, "General"),
		entry(SETTINGS_ITEM_PICKUP_TAB_APPEARANCE, "Appearance"),
		entry(SETTINGS_ITEM_PICKUP_TAB_BEHAVIOR, "Behavior"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_APPEARANCE, "Appearance"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_BEHAVIOR, "Behavior"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_TEXT, "Text"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_ANIMATION, "Animation"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_LAYOUT, "Layout"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION, "Presentation"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION_DESCRIPTION,
			"Shows pickups as a vertical list or a horizontal row of cards."),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH, "Stable Width"),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH_DESCRIPTION,
			"Keeps list notifications the same width when item names change."),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE, "UI Scale"),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE_DESCRIPTION,
			"Changes the size of the entire pickup display."),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING, "Row Spacing"),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING_DESCRIPTION,
			"Sets the space between list rows or cards."),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON, "Show Item Icon"),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON_DESCRIPTION,
			"Shows the item icon beside text in Detailed list mode."),
		entry(SETTINGS_ITEM_PICKUP_STYLE, "Content Mode"),
		entry(SETTINGS_ITEM_PICKUP_STYLE_DESCRIPTION,
			"Detailed shows the item name; Compact shows only the icon and amount."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE, "Background Style"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE_DESCRIPTION,
			"Shows separate tinted rows, no background, or one unified panel."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR, "Background Color"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR_DESCRIPTION,
			"Sets the color and transparency of the notification background."),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT, "Count Format"),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT_DESCRIPTION,
			"Chooses whether pickup amounts are displayed as +3 or x3."),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE, "Max Items Visible"),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE_DESCRIPTION, "Maximum number of items shown at once."),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME, "Display Time"),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME_DESCRIPTION,
			"Time before item notifications start disappearing."),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY, "Remove Delay"),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY_DESCRIPTION,
			"Delay after one notification is removed before the next starts disappearing."),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE, "Removal Mode"),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE_DESCRIPTION,
			"Removes notifications immediately or fades them out smoothly."),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION, "Fade Duration"),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION_DESCRIPTION,
			"Controls how quickly a notification fades out. Lower values fade faster."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW, "Merge Window"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW_DESCRIPTION,
			"Combines matching item pickups received within this time and resets their display time. Set to 0 to disable."),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR, "Text Color"),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR_DESCRIPTION, "Sets the pickup notification text color."),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION, "Growth Direction"),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION_DESCRIPTION,
			"Chooses where older pickups move. Auto grows away from the nearest screen edge."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION, "Entry Animation"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DESCRIPTION,
			"Slides pickups into place or shows them instantly."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION, "Entry Speed"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION_DESCRIPTION,
			"Controls how long the entry slide takes."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK, "Merge Feedback"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK_DESCRIPTION,
			"Pulses the amount when matching pickups are combined."),
		entry(COLOR_PICKER_ALPHA, "Alpha"),
		entry(COLOR_PICKER_INPUT, "Color value"),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertical"),
		entry(SETTINGS_VALUE_GROUPED, "Grouped"),
		entry(SETTINGS_VALUE_INDIVIDUAL, "Individual"),
		entry(SETTINGS_VALUE_CLEAR, "No Background"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventory"),
		entry(SETTINGS_VALUE_HOTBAR, "Hotbar"),
		entry(SETTINGS_VALUE_NONE, "Hidden"),
		entry(SETTINGS_VALUE_VALUE, "Value"),
		entry(SETTINGS_VALUE_PERCENT, "Percentage"),
		entry(SETTINGS_VALUE_TOP, "Top"),
		entry(SETTINGS_VALUE_BOTTOM, "Bottom"),
		entry(SETTINGS_VALUE_LEFT, "Left"),
		entry(SETTINGS_VALUE_RIGHT, "Right"),
		entry(SETTINGS_VALUE_CENTER, "Center"),
		entry(SETTINGS_VALUE_COLOR, "Color"),
		entry(SETTINGS_VALUE_PULSE, "Pulse"),
		entry(SETTINGS_VALUE_FLASH, "Flash"),
		entry(SETTINGS_VALUE_NORMAL, "Detailed"),
		entry(SETTINGS_VALUE_COMPACT, "Compact"),
		entry(SETTINGS_VALUE_PLUS_COUNT, "+ Number"),
		entry(SETTINGS_VALUE_MULTIPLY_COUNT, "x Number"),
		entry(SETTINGS_VALUE_TINTED_ROWS, "Tinted Rows"),
		entry(SETTINGS_VALUE_BACKGROUND_CLEAR, "Clear"),
		entry(SETTINGS_VALUE_UNIFIED_PANEL, "Unified Panel"),
		entry(SETTINGS_VALUE_INSTANT, "Instant"),
		entry(SETTINGS_VALUE_FADE_OUT, "Fade Out"),
		entry(SETTINGS_VALUE_LIST, "List"),
		entry(SETTINGS_VALUE_CARDS, "Cards"),
		entry(SETTINGS_VALUE_AUTO, "Auto"),
		entry(SETTINGS_VALUE_SLIDE, "Slide")
	), "en_us"),
	DE(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "HUD-Layout-Editor öffnen"),
		entry(MODULE_ARMOR, "Rüstungs-HUD"),
		entry(MODULE_ITEM_PICKUP, "Gegenstandsaufnahme HUD"),
		entry(EDITOR_TITLE, "HUD-Layout-Editor"),
		entry(EDITOR_INSTRUCTIONS,
			"Ziehen zum Verschieben. Linke Alt-Taste: Rasterfang. Umschalt-Klick: Schnelleinstellungen."),
		entry(EDITOR_RESET, "Zurücksetzen"),
		entry(EDITOR_SAVE_FAILED, "Änderungen konnten nicht gespeichert werden."),
		entry(EDITOR_VANILLA_HUD_AREA, "Vanilla-HUD-Bereich"),
		entry(EDITOR_SETTINGS_OPEN, "Globale Einstellungen"),
		entry(EDITOR_SETTINGS_TITLE, "Globale Einstellungen"),
		entry(EDITOR_SETTINGS_TAB_GENERAL, "Allgemein"),
		entry(EDITOR_SETTINGS_TAB_GRID, "Raster"),
		entry(EDITOR_SETTINGS_TAB_MODULES, "Module"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED, "%s aktiviert"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED_DESCRIPTION,
			"Schaltet %s ein oder aus, ohne die gespeicherten Einstellungen zu ändern."),
		entry(EDITOR_SETTINGS_MODULE_RESET, "%s zurücksetzen"),
		entry(EDITOR_SETTINGS_MODULE_RESET_DESCRIPTION,
			"Setzt die Einstellungen und das Layout dieses Moduls auf die Standardwerte zurück."),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL, "Alle Module zurücksetzen"),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL_DESCRIPTION,
			"Setzt alle HUD-Module zurück, ohne die Editoreinstellungen zu ändern."),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR, "Feines Raster"),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR_DESCRIPTION, "Legt die Farbe der 5-Pixel-Rasterlinien fest."),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR, "Grobes Raster"),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR_DESCRIPTION, "Legt die Farbe der 20-Pixel-Rasterlinien fest."),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR, "Mittellinien"),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR_DESCRIPTION,
			"Legt die Farbe der horizontalen und vertikalen Mittellinien fest."),
		entry(POPOVER_NO_SETTINGS, "Keine Schnelleinstellungen verfügbar."),
		entry(SETTINGS_TAB_LAYOUT, "Layout"),
		entry(SETTINGS_TAB_BAR, "Leiste"),
		entry(SETTINGS_TAB_TEXT, "Text"),
		entry(SETTINGS_SECTION_LAYOUT, "Layout"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Haltbarkeitsleiste"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Haltbarkeitstext"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Warnung bei niedriger Haltbarkeit"),
		entry(SETTINGS_SECTION_COLORS, "Farben"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE, "Layout-Modus"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE_DESCRIPTION,
			"Bewegt das Rüstungs-HUD als Gruppe oder positioniert jeden Rüstungsslot einzeln."),
		entry(SETTINGS_ARMOR_ORIENTATION, "Ausrichtung"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION,
			"Ordnet die Rüstungsslots horizontal oder vertikal an."),
		entry(SETTINGS_ARMOR_SCALE, "Skalierung"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Ändert die Größe des gesamten Rüstungs-HUDs."),
		entry(SETTINGS_ARMOR_SPACING, "Slot-Abstand"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Legt den Abstand zwischen Rüstungsslots fest."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Slot-Stil"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION, "Legt den Hintergrundstil der Rüstungsslots fest."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Leere Slots anzeigen"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION,
			"Zeigt Slots auch an, wenn keine Rüstung ausgerüstet ist."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Sichtbare Slots zentrieren"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Zentriert ausgerüstete Rüstungsslots, wenn leere Slots ausgeblendet sind."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Haltbarkeitsleiste anzeigen"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Zeigt eine Haltbarkeitsleiste für beschädigbare Rüstung an."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Leistenhöhe"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Legt die Höhe der Haltbarkeitsleiste fest."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Horizontaler Innenabstand"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Fügt horizontalen Abstand innerhalb der Haltbarkeitsleiste hinzu."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR, "Hintergrund"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR_DESCRIPTION,
			"Legt die Hintergrundfarbe der Haltbarkeitsleiste fest."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR, "Gesund"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR_DESCRIPTION,
			"Legt die Farbe für hohe Haltbarkeit fest."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR, "Warnung"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR_DESCRIPTION,
			"Legt die Farbe für mittlere Haltbarkeit fest."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR, "Kritisch"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR_DESCRIPTION,
			"Legt die Farbe für niedrige Haltbarkeit fest."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Textanzeige"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Zeigt die Haltbarkeit ausgeblendet, als Wert oder als Prozentzahl an."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Textposition"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Positioniert den Haltbarkeitstext relativ zum Rüstungsslot."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Textskalierung"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Ändert die Größe des Haltbarkeitstextes."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Textschatten"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Zeichnet einen Schatten hinter dem Haltbarkeitstext."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Text nach Haltbarkeit färben"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Verwendet Farben für gesunde, warnende und kritische Haltbarkeit."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR, "Textfarbe"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR_DESCRIPTION,
			"Legt die feste Farbe des Haltbarkeitstextes fest."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR, "Gesunder Text"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR_DESCRIPTION,
			"Legt die Textfarbe für hohe Haltbarkeit fest."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR, "Warntext"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR_DESCRIPTION,
			"Legt die Textfarbe für mittlere Haltbarkeit fest."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR, "Kritischer Text"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR_DESCRIPTION,
			"Legt die Textfarbe für niedrige Haltbarkeit fest."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Warnung anzeigen"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Hebt Rüstung am oder unter dem Grenzwert hervor."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Warngrenzwert"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Legt den Haltbarkeitswert fest, ab dem gewarnt wird."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Warnstil"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Legt die Animation der Haltbarkeitswarnung fest."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR, "Warnfarbe"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR_DESCRIPTION,
			"Legt die Hervorhebungsfarbe bei niedriger Haltbarkeit fest."),
		entry(COLOR_PICKER_ALPHA, "Alpha"),
		entry(COLOR_PICKER_INPUT, "Farbwert"),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertikal"),
		entry(SETTINGS_VALUE_GROUPED, "Gruppiert"),
		entry(SETTINGS_VALUE_INDIVIDUAL, "Einzeln"),
		entry(SETTINGS_VALUE_CLEAR, "Ohne Hintergrund"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventar"),
		entry(SETTINGS_VALUE_HOTBAR, "Schnellleiste"),
		entry(SETTINGS_VALUE_NONE, "Ausgeblendet"),
		entry(SETTINGS_VALUE_VALUE, "Wert"),
		entry(SETTINGS_VALUE_PERCENT, "Prozent"),
		entry(SETTINGS_VALUE_TOP, "Oben"),
		entry(SETTINGS_VALUE_BOTTOM, "Unten"),
		entry(SETTINGS_VALUE_LEFT, "Links"),
		entry(SETTINGS_VALUE_RIGHT, "Rechts"),
		entry(SETTINGS_VALUE_CENTER, "Mitte"),
		entry(SETTINGS_VALUE_COLOR, "Farbe"),
		entry(SETTINGS_VALUE_PULSE, "Pulsieren"),
		entry(SETTINGS_VALUE_FLASH, "Blinken"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR, "Akzentfarbe"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR_DESCRIPTION,
			"Legt die Akzentfarbe für Registerkarten, Regler und interaktive Steuerelemente fest."),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR, "Farbe der Modulrahmen"),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR_DESCRIPTION,
			"Legt die Rahmenfarbe für sichtbare HUD-Module im Layout-Editor fest."),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR, "Hervorhebungsfarbe der Module"),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR_DESCRIPTION,
			"Legt die Hervorhebungsfarbe für ausgewählte oder berührte HUD-Module fest."),
		entry(SETTINGS_ITEM_PICKUP_TAB_GENERAL, "Allgemein"),
		entry(SETTINGS_ITEM_PICKUP_TAB_APPEARANCE, "Darstellung"),
		entry(SETTINGS_ITEM_PICKUP_TAB_BEHAVIOR, "Verhalten"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_APPEARANCE, "Darstellung"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_BEHAVIOR, "Verhalten"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_TEXT, "Text"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_ANIMATION, "Animation"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_LAYOUT, "Layout"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION, "Darstellung"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION_DESCRIPTION,
			"Zeigt Aufnahmen als vertikale Liste oder horizontale Kartenreihe."),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH, "Stabile Breite"),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH_DESCRIPTION,
			"Behält bei wechselnden Gegenstandsnamen dieselbe Breite der Listenhinweise bei."),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE, "UI-Skalierung"),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE_DESCRIPTION,
			"Ändert die Größe der gesamten Aufnahmeanzeige."),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING, "Zeilenabstand"),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING_DESCRIPTION,
			"Legt den Abstand zwischen Listenzeilen oder Karten fest."),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON, "Gegenstandssymbol anzeigen"),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON_DESCRIPTION,
			"Zeigt im detaillierten Listenmodus das Gegenstandssymbol neben dem Text."),
		entry(SETTINGS_ITEM_PICKUP_STYLE, "Inhaltsmodus"),
		entry(SETTINGS_ITEM_PICKUP_STYLE_DESCRIPTION,
			"Detailliert zeigt den Gegenstandsnamen; Kompakt zeigt nur Symbol und Menge."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE, "Hintergrundstil"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE_DESCRIPTION,
			"Zeigt einzelne getönte Zeilen, keinen Hintergrund oder ein einheitliches Feld."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR, "Hintergrundfarbe"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR_DESCRIPTION,
			"Legt Farbe und Transparenz des Benachrichtigungshintergrunds fest."),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT, "Mengenformat"),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT_DESCRIPTION,
			"Legt fest, ob Aufnahmemengen als +3 oder x3 angezeigt werden."),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE, "Maximal sichtbare Gegenstände"),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE_DESCRIPTION,
			"Maximale Anzahl gleichzeitig angezeigter Gegenstände."),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME, "Anzeigedauer"),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME_DESCRIPTION,
			"Zeit, bevor Gegenstandsbenachrichtigungen ausgeblendet werden."),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY, "Entfernungsverzögerung"),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY_DESCRIPTION,
			"Verzögerung nach dem Entfernen eines Gegenstand, bevor der nächste verschwindet."),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE, "Entfernungsmodus"),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE_DESCRIPTION,
			"Entfernt Hinweise sofort oder blendet sie sanft aus."),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION, "Ausblenddauer"),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION_DESCRIPTION,
			"Steuert die Ausblendgeschwindigkeit. Niedrigere Werte blenden schneller aus."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW, "Zusammenführungszeitraum"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW_DESCRIPTION,
			"Kombiniert gleiche Gegenstände innerhalb dieser Zeit und setzt ihre Anzeigedauer zurück. 0 deaktiviert dies."),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR, "Textfarbe"),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR_DESCRIPTION,
			"Legt die Textfarbe der Aufnahmebenachrichtigungen fest."),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION, "Wachstumsrichtung"),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION_DESCRIPTION,
			"Legt fest, wohin ältere Aufnahmen verschoben werden. Automatisch wächst vom nächsten Bildschirmrand weg."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION, "Eingangsanimation"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DESCRIPTION,
			"Schiebt Aufnahmen an ihre Position oder zeigt sie sofort."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION, "Eingangsgeschwindigkeit"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION_DESCRIPTION,
			"Steuert die Dauer der Eingangsanimation."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK, "Zusammenführungsfeedback"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK_DESCRIPTION,
			"Lässt die Menge pulsieren, wenn gleiche Aufnahmen kombiniert werden."),
		entry(SETTINGS_VALUE_NORMAL, "Detailliert"),
		entry(SETTINGS_VALUE_COMPACT, "Kompakt"),
		entry(SETTINGS_VALUE_PLUS_COUNT, "+ Zahl"),
		entry(SETTINGS_VALUE_MULTIPLY_COUNT, "x Zahl"),
		entry(SETTINGS_VALUE_TINTED_ROWS, "Getönte Zeilen"),
		entry(SETTINGS_VALUE_BACKGROUND_CLEAR, "Ohne Hintergrund"),
		entry(SETTINGS_VALUE_UNIFIED_PANEL, "Einheitliches Feld"),
		entry(SETTINGS_VALUE_INSTANT, "Sofort"),
		entry(SETTINGS_VALUE_FADE_OUT, "Ausblenden"),
		entry(SETTINGS_VALUE_LIST, "Liste"),
		entry(SETTINGS_VALUE_CARDS, "Karten"),
		entry(SETTINGS_VALUE_AUTO, "Automatisch"),
		entry(SETTINGS_VALUE_SLIDE, "Gleiten")
	), "de_de", "de_at"),
	ES(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "Abrir el editor de diseños del HUD"),
		entry(MODULE_ARMOR, "HUD de armadura"),
		entry(MODULE_ITEM_PICKUP, "HUD de recogida de objetos"),
		entry(EDITOR_TITLE, "Editor de diseño de HUD"),
		entry(EDITOR_INSTRUCTIONS,
			"Arrastra para mover. Alt izquierdo: ajuste a cuadrícula. Mayús-clic: ajustes rápidos."),
		entry(EDITOR_RESET, "Restablecer"),
		entry(EDITOR_SAVE_FAILED, "No se han podido guardar los cambios."),
		entry(EDITOR_VANILLA_HUD_AREA, "Área del HUD original"),
		entry(EDITOR_SETTINGS_OPEN, "Ajustes globales"),
		entry(EDITOR_SETTINGS_TITLE, "Ajustes globales"),
		entry(EDITOR_SETTINGS_TAB_GENERAL, "General"),
		entry(EDITOR_SETTINGS_TAB_GRID, "Cuadrícula"),
		entry(EDITOR_SETTINGS_TAB_MODULES, "Módulos"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED, "%s activado"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED_DESCRIPTION,
			"Activa o desactiva %s sin cambiar sus ajustes guardados."),
		entry(EDITOR_SETTINGS_MODULE_RESET, "Restablecer %s"),
		entry(EDITOR_SETTINGS_MODULE_RESET_DESCRIPTION,
			"Restaura los ajustes y el diseño de este módulo a sus valores predeterminados."),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL, "Restablecer todos los módulos"),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL_DESCRIPTION,
			"Restaura todos los módulos del HUD sin cambiar los ajustes del editor."),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR, "Cuadrícula menor"),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR_DESCRIPTION,
			"Define el color de las líneas de cuadrícula de cinco píxeles."),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR, "Cuadrícula mayor"),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR_DESCRIPTION,
			"Define el color de las líneas de cuadrícula de veinte píxeles."),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR, "Guías centrales"),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR_DESCRIPTION,
			"Define el color de las guías centrales horizontal y vertical."),
		entry(POPOVER_NO_SETTINGS, "No hay ajustes rápidos disponibles."),
		entry(SETTINGS_TAB_LAYOUT, "Diseño"),
		entry(SETTINGS_TAB_BAR, "Barra"),
		entry(SETTINGS_TAB_TEXT, "Texto"),
		entry(SETTINGS_SECTION_LAYOUT, "Diseño"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Barra de durabilidad"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Texto de durabilidad"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Aviso de poca durabilidad"),
		entry(SETTINGS_SECTION_COLORS, "Colores"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE, "Modo de diseño"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE_DESCRIPTION,
			"Mueve el HUD de armadura como un grupo o permite colocar cada ranura por separado."),
		entry(SETTINGS_ARMOR_ORIENTATION, "Orientación"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION,
			"Organiza las ranuras de armadura horizontal o verticalmente."),
		entry(SETTINGS_ARMOR_SCALE, "Escala"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Cambia el tamaño de todo el HUD de armadura."),
		entry(SETTINGS_ARMOR_SPACING, "Espaciado de ranuras"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Controla el espacio entre las ranuras de armadura."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Estilo de ranura"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION,
			"Selecciona el estilo de fondo de las ranuras de armadura."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Mostrar ranuras vacías"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION,
			"Muestra las ranuras incluso cuando no hay armadura equipada."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Centrar ranuras visibles"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Centra las ranuras equipadas cuando las ranuras vacías están ocultas."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Mostrar barra de durabilidad"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Muestra una barra de durabilidad para la armadura que puede dañarse."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Altura de la barra"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Controla la altura de la barra de durabilidad."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Relleno horizontal"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Añade espacio horizontal dentro de la barra de durabilidad."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR, "Fondo"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR_DESCRIPTION,
			"Establece el color de fondo de la barra de durabilidad."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR, "Saludable"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR_DESCRIPTION,
			"Establece el color para una durabilidad alta."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR, "Aviso"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR_DESCRIPTION,
			"Establece el color para una durabilidad media."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR, "Crítico"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR_DESCRIPTION,
			"Establece el color para una durabilidad baja."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Visualización del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Muestra la durabilidad oculta, como valor o como porcentaje."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Posición del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Coloca el texto de durabilidad respecto a cada ranura de armadura."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Escala del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Cambia el tamaño del texto de durabilidad."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Sombra del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Dibuja una sombra detrás del texto de durabilidad."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Colorear texto por durabilidad"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Usa colores saludable, de aviso y crítico para el texto."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR, "Color del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR_DESCRIPTION,
			"Establece el color fijo del texto de durabilidad."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR, "Texto saludable"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR_DESCRIPTION,
			"Establece el color del texto para una durabilidad alta."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR, "Texto de aviso"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR_DESCRIPTION,
			"Establece el color del texto para una durabilidad media."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR, "Texto crítico"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR_DESCRIPTION,
			"Establece el color del texto para una durabilidad baja."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Mostrar aviso de poca durabilidad"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Resalta la armadura cuya durabilidad está en el umbral o por debajo."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Umbral de aviso"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Establece el porcentaje de durabilidad que activa el aviso."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Estilo del aviso"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Selecciona cómo se anima el aviso de poca durabilidad."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR, "Color del aviso"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR_DESCRIPTION,
			"Establece el color de resaltado de poca durabilidad."),
		entry(COLOR_PICKER_ALPHA, "Alfa"),
		entry(COLOR_PICKER_INPUT, "Valor de color"),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertical"),
		entry(SETTINGS_VALUE_GROUPED, "Agrupado"),
		entry(SETTINGS_VALUE_INDIVIDUAL, "Individual"),
		entry(SETTINGS_VALUE_CLEAR, "Sin fondo"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventario"),
		entry(SETTINGS_VALUE_HOTBAR, "Barra rápida"),
		entry(SETTINGS_VALUE_NONE, "Oculto"),
		entry(SETTINGS_VALUE_VALUE, "Valor"),
		entry(SETTINGS_VALUE_PERCENT, "Porcentaje"),
		entry(SETTINGS_VALUE_TOP, "Arriba"),
		entry(SETTINGS_VALUE_BOTTOM, "Abajo"),
		entry(SETTINGS_VALUE_LEFT, "Izquierda"),
		entry(SETTINGS_VALUE_RIGHT, "Derecha"),
		entry(SETTINGS_VALUE_CENTER, "Centro"),
		entry(SETTINGS_VALUE_COLOR, "Color"),
		entry(SETTINGS_VALUE_PULSE, "Pulso"),
		entry(SETTINGS_VALUE_FLASH, "Destello"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR, "Color de acento"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR_DESCRIPTION,
			"Establece el color de acento de pestañas, controles deslizantes y controles interactivos."),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR, "Color del borde de los módulos"),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR_DESCRIPTION,
			"Establece el color del borde de los módulos HUD visibles en el editor de diseño."),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR, "Color de resaltado de los módulos"),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR_DESCRIPTION,
			"Establece el color de resaltado de los módulos HUD seleccionados o señalados."),
		entry(SETTINGS_ITEM_PICKUP_TAB_GENERAL, "General"),
		entry(SETTINGS_ITEM_PICKUP_TAB_APPEARANCE, "Apariencia"),
		entry(SETTINGS_ITEM_PICKUP_TAB_BEHAVIOR, "Comportamiento"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_APPEARANCE, "Apariencia"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_BEHAVIOR, "Comportamiento"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_TEXT, "Texto"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_ANIMATION, "Animación"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_LAYOUT, "Diseño"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION, "Presentación"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION_DESCRIPTION,
			"Muestra las recogidas como una lista vertical o una fila horizontal de tarjetas."),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH, "Ancho estable"),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH_DESCRIPTION,
			"Mantiene el mismo ancho de las notificaciones cuando cambia el nombre del objeto."),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE, "Escala de interfaz"),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE_DESCRIPTION,
			"Cambia el tamaño de toda la interfaz de recogidas."),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING, "Espaciado de filas"),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING_DESCRIPTION,
			"Establece el espacio entre filas de la lista o tarjetas."),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON, "Mostrar icono del objeto"),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON_DESCRIPTION,
			"Muestra el icono del objeto junto al texto en el modo de lista detallado."),
		entry(SETTINGS_ITEM_PICKUP_STYLE, "Modo de contenido"),
		entry(SETTINGS_ITEM_PICKUP_STYLE_DESCRIPTION,
			"Detallado muestra el nombre del objeto; Compacto muestra solo el icono y la cantidad."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE, "Estilo de fondo"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE_DESCRIPTION,
			"Muestra filas coloreadas separadas, ningún fondo o un panel unificado."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR, "Color de fondo"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR_DESCRIPTION,
			"Establece el color y la transparencia del fondo de las notificaciones."),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT, "Formato de cantidad"),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT_DESCRIPTION,
			"Elige si las cantidades recogidas se muestran como +3 o x3."),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE, "Número máximo de elementos visibles"),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE_DESCRIPTION,
			"Número máximo de objetos mostrados a la vez."),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME, "Tiempo de visualización"),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME_DESCRIPTION,
			"Tiempo antes de que las notificaciones de objetos empiecen a desaparecer."),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY, "Retraso de eliminación"),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY_DESCRIPTION,
			"Retraso después de eliminar una notificación antes de que la siguiente empiece a desaparecer."),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE, "Modo de eliminación"),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE_DESCRIPTION,
			"Elimina las notificaciones al instante o las desvanece suavemente."),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION, "Duración del desvanecimiento"),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION_DESCRIPTION,
			"Controla la velocidad del desvanecimiento. Los valores bajos son más rápidos."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW, "Intervalo de combinación"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW_DESCRIPTION,
			"Combina objetos iguales recibidos durante este intervalo y reinicia su tiempo. Usa 0 para desactivarlo."),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR, "Color del texto"),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR_DESCRIPTION,
			"Establece el color del texto de las notificaciones de recogida."),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION, "Dirección de crecimiento"),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION_DESCRIPTION,
			"Elige hacia dónde se mueven las recogidas anteriores. Automático se aleja del borde más cercano."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION, "Animación de entrada"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DESCRIPTION,
			"Desliza las recogidas a su posición o las muestra al instante."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION, "Velocidad de entrada"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION_DESCRIPTION,
			"Controla cuánto dura el deslizamiento de entrada."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK, "Respuesta al combinar"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK_DESCRIPTION,
			"Hace pulsar la cantidad cuando se combinan recogidas iguales."),
		entry(SETTINGS_VALUE_NORMAL, "Detallado"),
		entry(SETTINGS_VALUE_COMPACT, "Compacto"),
		entry(SETTINGS_VALUE_PLUS_COUNT, "+ Número"),
		entry(SETTINGS_VALUE_MULTIPLY_COUNT, "x Número"),
		entry(SETTINGS_VALUE_TINTED_ROWS, "Filas coloreadas"),
		entry(SETTINGS_VALUE_BACKGROUND_CLEAR, "Sin fondo"),
		entry(SETTINGS_VALUE_UNIFIED_PANEL, "Panel unificado"),
		entry(SETTINGS_VALUE_INSTANT, "Instantáneo"),
		entry(SETTINGS_VALUE_FADE_OUT, "Desvanecer"),
		entry(SETTINGS_VALUE_LIST, "Lista"),
		entry(SETTINGS_VALUE_CARDS, "Tarjetas"),
		entry(SETTINGS_VALUE_AUTO, "Automático"),
		entry(SETTINGS_VALUE_SLIDE, "Deslizar")
	), "es_mx", "es_es"),
	FR_FR(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "Ouvrir l'éditeur de mise en page HUD"),
		entry(MODULE_ARMOR, "Affichage tête haute de l'armure"),
		entry(MODULE_ITEM_PICKUP, "HUD pour la détection d'objets"),
		entry(EDITOR_TITLE, "Éditeur de mise en page HUD"),
		entry(EDITOR_INSTRUCTIONS,
			"Glisser pour déplacer. Alt gauche : aimantation à la grille. Maj-clic : réglages rapides."),
		entry(EDITOR_RESET, "Réinitialiser"),
		entry(EDITOR_SAVE_FAILED, "Les modifications n'ont pas pu être enregistrées."),
		entry(EDITOR_VANILLA_HUD_AREA, "Zone de l'interface classique"),
		entry(EDITOR_SETTINGS_OPEN, "Réglages globaux"),
		entry(EDITOR_SETTINGS_TITLE, "Réglages globaux"),
		entry(EDITOR_SETTINGS_TAB_GENERAL, "Général"),
		entry(EDITOR_SETTINGS_TAB_GRID, "Grille"),
		entry(EDITOR_SETTINGS_TAB_MODULES, "Modules"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED, "%s activé"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED_DESCRIPTION,
			"Active ou désactive %s sans modifier ses réglages enregistrés."),
		entry(EDITOR_SETTINGS_MODULE_RESET, "Réinitialiser %s"),
		entry(EDITOR_SETTINGS_MODULE_RESET_DESCRIPTION,
			"Restaure les réglages et la disposition de ce module par défaut."),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL, "Réinitialiser tous les modules"),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL_DESCRIPTION,
			"Restaure tous les modules du HUD sans modifier les réglages de l'éditeur."),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR, "Grille secondaire"),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR_DESCRIPTION,
			"Définit la couleur des lignes de grille espacées de cinq pixels."),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR, "Grille principale"),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR_DESCRIPTION,
			"Définit la couleur des lignes de grille espacées de vingt pixels."),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR, "Guides centraux"),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR_DESCRIPTION,
			"Définit la couleur des guides centraux horizontal et vertical."),
		entry(POPOVER_NO_SETTINGS, "Aucun réglage rapide disponible."),
		entry(SETTINGS_TAB_LAYOUT, "Disposition"),
		entry(SETTINGS_TAB_BAR, "Barre"),
		entry(SETTINGS_TAB_TEXT, "Texte"),
		entry(SETTINGS_SECTION_LAYOUT, "Disposition"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Barre de durabilité"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Texte de durabilité"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Alerte de faible durabilité"),
		entry(SETTINGS_SECTION_COLORS, "Couleurs"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE, "Mode de disposition"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE_DESCRIPTION,
			"Déplace l'affichage de l'armure en groupe ou positionne chaque emplacement séparément."),
		entry(SETTINGS_ARMOR_ORIENTATION, "Orientation"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION,
			"Dispose les emplacements d'armure horizontalement ou verticalement."),
		entry(SETTINGS_ARMOR_SCALE, "Échelle"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Modifie la taille de tout l'affichage de l'armure."),
		entry(SETTINGS_ARMOR_SPACING, "Espacement des emplacements"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Contrôle l'espace entre les emplacements d'armure."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Style des emplacements"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION,
			"Sélectionne le style d'arrière-plan des emplacements d'armure."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Afficher les emplacements vides"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION,
			"Affiche les emplacements même lorsqu'aucune armure n'est équipée."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Centrer les emplacements visibles"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Centre les emplacements équipés lorsque les emplacements vides sont masqués."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Afficher la barre de durabilité"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Affiche une barre de durabilité pour les pièces d'armure endommageables."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Hauteur de la barre"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Contrôle la hauteur de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Marge intérieure horizontale"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Ajoute un espace horizontal à l'intérieur de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR, "Arrière-plan"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR_DESCRIPTION,
			"Définit la couleur de fond de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR, "Saine"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR_DESCRIPTION,
			"Définit la couleur utilisée pour une durabilité élevée."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR, "Alerte"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR_DESCRIPTION,
			"Définit la couleur utilisée pour une durabilité moyenne."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR, "Critique"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR_DESCRIPTION,
			"Définit la couleur utilisée pour une durabilité faible."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Affichage du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Masque la durabilité ou l'affiche en valeur ou en pourcentage."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Position du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Place le texte de durabilité par rapport à chaque emplacement."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Échelle du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Modifie la taille du texte de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Ombre du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Ajoute une ombre derrière le texte de durabilité."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Colorer le texte selon la durabilité"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Utilise les couleurs saine, d'alerte et critique pour le texte."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR, "Couleur du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR_DESCRIPTION,
			"Définit la couleur fixe du texte de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR, "Texte sain"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR_DESCRIPTION,
			"Définit la couleur du texte pour une durabilité élevée."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR, "Texte d'alerte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR_DESCRIPTION,
			"Définit la couleur du texte pour une durabilité moyenne."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR, "Texte critique"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR_DESCRIPTION,
			"Définit la couleur du texte pour une durabilité faible."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Afficher l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Met en évidence l'armure dont la durabilité atteint le seuil."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Seuil d'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Définit le pourcentage de durabilité qui déclenche l'alerte."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Style de l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Sélectionne l'animation de l'alerte de faible durabilité."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR, "Couleur de l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR_DESCRIPTION,
			"Définit la couleur de surbrillance de faible durabilité."),
		entry(COLOR_PICKER_ALPHA, "Alpha"),
		entry(COLOR_PICKER_INPUT, "Valeur de couleur"),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertical"),
		entry(SETTINGS_VALUE_GROUPED, "Groupé"),
		entry(SETTINGS_VALUE_INDIVIDUAL, "Individuel"),
		entry(SETTINGS_VALUE_CLEAR, "Sans arrière-plan"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventaire"),
		entry(SETTINGS_VALUE_HOTBAR, "Barre rapide"),
		entry(SETTINGS_VALUE_NONE, "Masqué"),
		entry(SETTINGS_VALUE_VALUE, "Valeur"),
		entry(SETTINGS_VALUE_PERCENT, "Pourcentage"),
		entry(SETTINGS_VALUE_TOP, "Haut"),
		entry(SETTINGS_VALUE_BOTTOM, "Bas"),
		entry(SETTINGS_VALUE_LEFT, "Gauche"),
		entry(SETTINGS_VALUE_RIGHT, "Droite"),
		entry(SETTINGS_VALUE_CENTER, "Centre"),
		entry(SETTINGS_VALUE_COLOR, "Couleur"),
		entry(SETTINGS_VALUE_PULSE, "Pulsation"),
		entry(SETTINGS_VALUE_FLASH, "Clignotement"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR, "Couleur d'accentuation"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR_DESCRIPTION,
			"Définit la couleur d'accentuation des onglets, curseurs et commandes interactives."),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR, "Couleur de bordure des modules"),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR_DESCRIPTION,
			"Définit la couleur de bordure des modules HUD visibles dans l'éditeur de disposition."),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR, "Couleur de surbrillance des modules"),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR_DESCRIPTION,
			"Définit la couleur de surbrillance des modules HUD sélectionnés ou survolés."),
		entry(SETTINGS_ITEM_PICKUP_TAB_GENERAL, "Général"),
		entry(SETTINGS_ITEM_PICKUP_TAB_APPEARANCE, "Apparence"),
		entry(SETTINGS_ITEM_PICKUP_TAB_BEHAVIOR, "Comportement"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_APPEARANCE, "Apparence"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_BEHAVIOR, "Comportement"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_TEXT, "Texte"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_ANIMATION, "Animation"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_LAYOUT, "Disposition"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION, "Présentation"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION_DESCRIPTION,
			"Affiche les ramassages sous forme de liste verticale ou de rangée horizontale de cartes."),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH, "Largeur stable"),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH_DESCRIPTION,
			"Conserve la même largeur de notification lorsque le nom de l'objet change."),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE, "Échelle de l'interface"),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE_DESCRIPTION,
			"Modifie la taille de l'ensemble de l'affichage des ramassages."),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING, "Espacement des rangées"),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING_DESCRIPTION,
			"Définit l'espace entre les rangées de liste ou les cartes."),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON, "Afficher l'icône de l'objet"),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON_DESCRIPTION,
			"Affiche l'icône de l'objet à côté du texte dans le mode liste détaillé."),
		entry(SETTINGS_ITEM_PICKUP_STYLE, "Mode de contenu"),
		entry(SETTINGS_ITEM_PICKUP_STYLE_DESCRIPTION,
			"Détaillé affiche le nom de l'objet ; Compact affiche uniquement l'icône et la quantité."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE, "Style d'arrière-plan"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE_DESCRIPTION,
			"Affiche des lignes teintées séparées, aucun arrière-plan ou un panneau unifié."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR, "Couleur d'arrière-plan"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR_DESCRIPTION,
			"Définit la couleur et la transparence de l'arrière-plan des notifications."),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT, "Format de quantité"),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT_DESCRIPTION,
			"Choisit si les quantités ramassées sont affichées sous la forme +3 ou x3."),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE, "Nombre maximal d'éléments affichés"),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE_DESCRIPTION,
			"Nombre maximal d'objets affichés simultanément."),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME, "Durée d'affichage"),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME_DESCRIPTION,
			"Délai avant que les notifications d'objets commencent à disparaître."),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY, "Délai de suppression"),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY_DESCRIPTION,
			"Délai après la suppression d'une notification avant que la suivante commence à disparaître."),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE, "Mode de suppression"),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE_DESCRIPTION,
			"Supprime les notifications instantanément ou les fait disparaître progressivement."),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION, "Durée du fondu"),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION_DESCRIPTION,
			"Contrôle la vitesse du fondu. Les valeurs plus faibles produisent un fondu plus rapide."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW, "Fenêtre de regroupement"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW_DESCRIPTION,
			"Regroupe les objets identiques reçus pendant cette durée et réinitialise leur délai. 0 désactive cette option."),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR, "Couleur du texte"),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR_DESCRIPTION,
			"Définit la couleur du texte des notifications de ramassage."),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION, "Direction d'extension"),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION_DESCRIPTION,
			"Détermine où vont les anciens ramassages. Auto s'éloigne du bord d'écran le plus proche."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION, "Animation d'entrée"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DESCRIPTION,
			"Fait glisser les ramassages en place ou les affiche instantanément."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION, "Vitesse d'entrée"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION_DESCRIPTION,
			"Contrôle la durée du glissement d'entrée."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK, "Retour de regroupement"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK_DESCRIPTION,
			"Fait pulser la quantité lorsque des ramassages identiques sont regroupés."),
		entry(SETTINGS_VALUE_NORMAL, "Détaillé"),
		entry(SETTINGS_VALUE_COMPACT, "Compact"),
		entry(SETTINGS_VALUE_PLUS_COUNT, "+ Nombre"),
		entry(SETTINGS_VALUE_MULTIPLY_COUNT, "x Nombre"),
		entry(SETTINGS_VALUE_TINTED_ROWS, "Lignes teintées"),
		entry(SETTINGS_VALUE_BACKGROUND_CLEAR, "Sans arrière-plan"),
		entry(SETTINGS_VALUE_UNIFIED_PANEL, "Panneau unifié"),
		entry(SETTINGS_VALUE_INSTANT, "Instantané"),
		entry(SETTINGS_VALUE_FADE_OUT, "Fondu"),
		entry(SETTINGS_VALUE_LIST, "Liste"),
		entry(SETTINGS_VALUE_CARDS, "Cartes"),
		entry(SETTINGS_VALUE_AUTO, "Auto"),
		entry(SETTINGS_VALUE_SLIDE, "Glissement")
	), "fr_fr"),
	FR_CA(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "Ouvrir l'éditeur de disposition HUD"),
		entry(MODULE_ARMOR, "Interface d'affichage de l'armure"),
		entry(MODULE_ITEM_PICKUP, "HUD pour la détection d'objets"),
		entry(EDITOR_TITLE, "Éditeur de mise en page HUD"),
		entry(EDITOR_INSTRUCTIONS,
			"Glisser pour déplacer. Alt gauche : aimantation à la grille. Maj-clic : réglages rapides."),
		entry(EDITOR_RESET, "Réinitialiser"),
		entry(EDITOR_SAVE_FAILED, "Les modifications n'ont pas pu être enregistrées."),
		entry(EDITOR_VANILLA_HUD_AREA, "Zone de l'interface classique"),
		entry(EDITOR_SETTINGS_OPEN, "Paramètres globaux"),
		entry(EDITOR_SETTINGS_TITLE, "Paramètres globaux"),
		entry(EDITOR_SETTINGS_TAB_GENERAL, "Général"),
		entry(EDITOR_SETTINGS_TAB_GRID, "Grille"),
		entry(EDITOR_SETTINGS_TAB_MODULES, "Modules"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED, "%s activé"),
		entry(EDITOR_SETTINGS_MODULE_ENABLED_DESCRIPTION,
			"Active ou désactive %s sans modifier ses paramètres enregistrés."),
		entry(EDITOR_SETTINGS_MODULE_RESET, "Réinitialiser %s"),
		entry(EDITOR_SETTINGS_MODULE_RESET_DESCRIPTION,
			"Restaure les paramètres et la disposition de ce module par défaut."),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL, "Réinitialiser tous les modules"),
		entry(EDITOR_SETTINGS_MODULES_RESET_ALL_DESCRIPTION,
			"Restaure tous les modules du HUD sans modifier les paramètres de l'éditeur."),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR, "Grille secondaire"),
		entry(EDITOR_SETTINGS_MINOR_GRID_COLOR_DESCRIPTION,
			"Définit la couleur des lignes de grille espacées de cinq pixels."),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR, "Grille principale"),
		entry(EDITOR_SETTINGS_MAJOR_GRID_COLOR_DESCRIPTION,
			"Définit la couleur des lignes de grille espacées de vingt pixels."),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR, "Guides centraux"),
		entry(EDITOR_SETTINGS_CENTER_GUIDE_COLOR_DESCRIPTION,
			"Définit la couleur des guides centraux horizontal et vertical."),
		entry(POPOVER_NO_SETTINGS, "Aucun réglage rapide disponible."),
		entry(SETTINGS_TAB_LAYOUT, "Disposition"),
		entry(SETTINGS_TAB_BAR, "Barre"),
		entry(SETTINGS_TAB_TEXT, "Texte"),
		entry(SETTINGS_SECTION_LAYOUT, "Disposition"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Barre de durabilité"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Texte de durabilité"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Alerte de faible durabilité"),
		entry(SETTINGS_SECTION_COLORS, "Couleurs"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE, "Mode de disposition"),
		entry(SETTINGS_ARMOR_LAYOUT_MODE_DESCRIPTION,
			"Déplace l'interface d'armure en groupe ou positionne chaque emplacement séparément."),
		entry(SETTINGS_ARMOR_ORIENTATION, "Orientation"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION,
			"Dispose les emplacements d'armure horizontalement ou verticalement."),
		entry(SETTINGS_ARMOR_SCALE, "Échelle"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Modifie la taille de toute l'interface d'armure."),
		entry(SETTINGS_ARMOR_SPACING, "Espacement des emplacements"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Contrôle l'espace entre les emplacements d'armure."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Style des emplacements"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION,
			"Sélectionne le style d'arrière-plan des emplacements d'armure."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Afficher les emplacements vides"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION,
			"Affiche les emplacements même lorsqu'aucune armure n'est équipée."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Centrer les emplacements visibles"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Centre les emplacements équipés lorsque les emplacements vides sont masqués."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Afficher la barre de durabilité"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Affiche une barre de durabilité pour les pièces d'armure endommageables."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Hauteur de la barre"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Contrôle la hauteur de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Marge intérieure horizontale"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Ajoute un espace horizontal à l'intérieur de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR, "Arrière-plan"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_BACKGROUND_COLOR_DESCRIPTION,
			"Définit la couleur de fond de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR, "Saine"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEALTHY_COLOR_DESCRIPTION,
			"Définit la couleur utilisée pour une durabilité élevée."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR, "Alerte"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_WARNING_COLOR_DESCRIPTION,
			"Définit la couleur utilisée pour une durabilité moyenne."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR, "Critique"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_CRITICAL_COLOR_DESCRIPTION,
			"Définit la couleur utilisée pour une durabilité faible."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Affichage du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Masque la durabilité ou l'affiche en valeur ou en pourcentage."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Position du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Place le texte de durabilité par rapport à chaque emplacement."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Échelle du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Modifie la taille du texte de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Ombre du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Ajoute une ombre derrière le texte de durabilité."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Colorer le texte selon la durabilité"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Utilise les couleurs saine, d'alerte et critique pour le texte."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR, "Couleur du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_COLOR_DESCRIPTION,
			"Définit la couleur fixe du texte de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR, "Texte sain"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_HEALTHY_COLOR_DESCRIPTION,
			"Définit la couleur du texte pour une durabilité élevée."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR, "Texte d'alerte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_WARNING_COLOR_DESCRIPTION,
			"Définit la couleur du texte pour une durabilité moyenne."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR, "Texte critique"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_CRITICAL_COLOR_DESCRIPTION,
			"Définit la couleur du texte pour une durabilité faible."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Afficher l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Met en évidence l'armure dont la durabilité atteint le seuil."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Seuil d'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Définit le pourcentage de durabilité qui déclenche l'alerte."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Style de l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Sélectionne l'animation de l'alerte de faible durabilité."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR, "Couleur de l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_COLOR_DESCRIPTION,
			"Définit la couleur de surbrillance de faible durabilité."),
		entry(COLOR_PICKER_ALPHA, "Alpha"),
		entry(COLOR_PICKER_INPUT, "Valeur de couleur"),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertical"),
		entry(SETTINGS_VALUE_GROUPED, "Groupé"),
		entry(SETTINGS_VALUE_INDIVIDUAL, "Individuel"),
		entry(SETTINGS_VALUE_CLEAR, "Sans arrière-plan"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventaire"),
		entry(SETTINGS_VALUE_HOTBAR, "Barre rapide"),
		entry(SETTINGS_VALUE_NONE, "Masqué"),
		entry(SETTINGS_VALUE_VALUE, "Valeur"),
		entry(SETTINGS_VALUE_PERCENT, "Pourcentage"),
		entry(SETTINGS_VALUE_TOP, "Haut"),
		entry(SETTINGS_VALUE_BOTTOM, "Bas"),
		entry(SETTINGS_VALUE_LEFT, "Gauche"),
		entry(SETTINGS_VALUE_RIGHT, "Droite"),
		entry(SETTINGS_VALUE_CENTER, "Centre"),
		entry(SETTINGS_VALUE_COLOR, "Couleur"),
		entry(SETTINGS_VALUE_PULSE, "Pulsation"),
		entry(SETTINGS_VALUE_FLASH, "Clignotement"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR, "Couleur d'accent"),
		entry(EDITOR_SETTINGS_ACCENT_COLOR_DESCRIPTION,
			"Définit la couleur d'accent des onglets, curseurs et contrôles interactifs."),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR, "Couleur de bordure des modules"),
		entry(EDITOR_SETTINGS_MODULE_BORDER_COLOR_DESCRIPTION,
			"Définit la couleur de bordure des modules HUD visibles dans l'éditeur de disposition."),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR, "Couleur de surbrillance des modules"),
		entry(EDITOR_SETTINGS_MODULE_HIGHLIGHT_COLOR_DESCRIPTION,
			"Définit la couleur de surbrillance des modules HUD sélectionnés ou survolés."),
		entry(SETTINGS_ITEM_PICKUP_TAB_GENERAL, "Général"),
		entry(SETTINGS_ITEM_PICKUP_TAB_APPEARANCE, "Apparence"),
		entry(SETTINGS_ITEM_PICKUP_TAB_BEHAVIOR, "Comportement"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_APPEARANCE, "Apparence"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_BEHAVIOR, "Comportement"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_TEXT, "Texte"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_ANIMATION, "Animation"),
		entry(SETTINGS_ITEM_PICKUP_SECTION_LAYOUT, "Disposition"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION, "Présentation"),
		entry(SETTINGS_ITEM_PICKUP_PRESENTATION_DESCRIPTION,
			"Affiche les collectes sous forme de liste verticale ou de rangée horizontale de cartes."),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH, "Largeur stable"),
		entry(SETTINGS_ITEM_PICKUP_STABLE_WIDTH_DESCRIPTION,
			"Conserve la même largeur de notification lorsque le nom de l'objet change."),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE, "Échelle de l'interface"),
		entry(SETTINGS_ITEM_PICKUP_UI_SCALE_DESCRIPTION,
			"Modifie la taille de l'ensemble de l'affichage des collectes."),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING, "Espacement des rangées"),
		entry(SETTINGS_ITEM_PICKUP_ROW_SPACING_DESCRIPTION,
			"Définit l'espace entre les rangées de liste ou les cartes."),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON, "Afficher l'icône de l'objet"),
		entry(SETTINGS_ITEM_PICKUP_SHOW_ITEM_ICON_DESCRIPTION,
			"Affiche l'icône de l'objet à côté du texte dans le mode liste détaillé."),
		entry(SETTINGS_ITEM_PICKUP_STYLE, "Mode de contenu"),
		entry(SETTINGS_ITEM_PICKUP_STYLE_DESCRIPTION,
			"Détaillé affiche le nom de l'objet ; Compact affiche seulement l'icône et la quantité."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE, "Style d'arrière-plan"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_STYLE_DESCRIPTION,
			"Affiche des rangées teintées séparées, aucun arrière-plan ou un panneau unifié."),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR, "Couleur d'arrière-plan"),
		entry(SETTINGS_ITEM_PICKUP_BACKGROUND_COLOR_DESCRIPTION,
			"Définit la couleur et la transparence de l'arrière-plan des notifications."),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT, "Format de quantité"),
		entry(SETTINGS_ITEM_PICKUP_COUNT_FORMAT_DESCRIPTION,
			"Choisit si les quantités collectées sont affichées sous la forme +3 ou x3."),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE, "Nombre maximal d'éléments affichés"),
		entry(SETTINGS_ITEM_PICKUP_MAX_VISIBLE_DESCRIPTION,
			"Nombre maximal d'objets affichés en même temps."),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME, "Durée d'affichage"),
		entry(SETTINGS_ITEM_PICKUP_DISPLAY_TIME_DESCRIPTION,
			"Délai avant que les notifications d'objets commencent à disparaître."),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY, "Délai de suppression"),
		entry(SETTINGS_ITEM_PICKUP_REMOVE_DELAY_DESCRIPTION,
			"Délai après la suppression d'une notification avant que la suivante commence à disparaître."),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE, "Mode de suppression"),
		entry(SETTINGS_ITEM_PICKUP_REMOVAL_MODE_DESCRIPTION,
			"Supprime les notifications instantanément ou les fait disparaître graduellement."),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION, "Durée du fondu"),
		entry(SETTINGS_ITEM_PICKUP_FADE_DURATION_DESCRIPTION,
			"Contrôle la vitesse du fondu. Les valeurs plus faibles produisent un fondu plus rapide."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW, "Fenêtre de regroupement"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_WINDOW_DESCRIPTION,
			"Regroupe les objets identiques reçus pendant cette durée et réinitialise leur délai. 0 désactive cette option."),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR, "Couleur du texte"),
		entry(SETTINGS_ITEM_PICKUP_TEXT_COLOR_DESCRIPTION,
			"Définit la couleur du texte des notifications de collecte."),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION, "Direction d'extension"),
		entry(SETTINGS_ITEM_PICKUP_GROWTH_DIRECTION_DESCRIPTION,
			"Détermine où vont les anciennes collectes. Auto s'éloigne du bord d'écran le plus proche."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION, "Animation d'entrée"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DESCRIPTION,
			"Fait glisser les collectes en place ou les affiche instantanément."),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION, "Vitesse d'entrée"),
		entry(SETTINGS_ITEM_PICKUP_ENTRY_ANIMATION_DURATION_DESCRIPTION,
			"Contrôle la durée du glissement d'entrée."),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK, "Retour de regroupement"),
		entry(SETTINGS_ITEM_PICKUP_MERGE_FEEDBACK_DESCRIPTION,
			"Fait pulser la quantité lorsque des collectes identiques sont regroupées."),
		entry(SETTINGS_VALUE_NORMAL, "Détaillé"),
		entry(SETTINGS_VALUE_COMPACT, "Compact"),
		entry(SETTINGS_VALUE_PLUS_COUNT, "+ Nombre"),
		entry(SETTINGS_VALUE_MULTIPLY_COUNT, "x Nombre"),
		entry(SETTINGS_VALUE_TINTED_ROWS, "Rangées teintées"),
		entry(SETTINGS_VALUE_BACKGROUND_CLEAR, "Sans arrière-plan"),
		entry(SETTINGS_VALUE_UNIFIED_PANEL, "Panneau unifié"),
		entry(SETTINGS_VALUE_INSTANT, "Instantané"),
		entry(SETTINGS_VALUE_FADE_OUT, "Fondu"),
		entry(SETTINGS_VALUE_LIST, "Liste"),
		entry(SETTINGS_VALUE_CARDS, "Cartes"),
		entry(SETTINGS_VALUE_AUTO, "Auto"),
		entry(SETTINGS_VALUE_SLIDE, "Glissement")
	), "fr_ca");

	static {
		Set<String> locales = new HashSet<>();
		for (HudLanguage language : values()) {
			if (language.locales.isEmpty()) {
				throw new IllegalStateException(language.name() + " has no locales");
			}
			for (String locale : language.locales) {
				if (!locales.add(locale)) {
					throw new IllegalStateException("Duplicate language locale: " + locale);
				}
			}
		}
		EN.requireComplete();
	}

	private final Map<TranslationKey, String> translations;
	private final List<String> locales;

	HudLanguage(Map<TranslationKey, String> translations, String... locales) {
		this.translations = translations;
		this.locales = List.of(locales);
	}

	public List<String> getLocales() {
		return locales;
	}

	public Map<TranslationKey, String> getTranslations() {
		return translations;
	}

	@SafeVarargs
	private static Map<TranslationKey, String> translations(Map.Entry<TranslationKey, String>... entries) {
		EnumMap<TranslationKey, String> values = new EnumMap<>(TranslationKey.class);
		for (Map.Entry<TranslationKey, String> entry : entries) {
			if (values.put(entry.getKey(), entry.getValue()) != null) {
				throw new IllegalStateException("Duplicate translation: " + entry.getKey().key());
			}
		}
		return Collections.unmodifiableMap(values);
	}

	private void requireComplete() {
		for (TranslationKey translation : TranslationKey.values()) {
			if (!translations.containsKey(translation)) {
				throw new IllegalStateException(locales.getFirst() + " is missing translation " + translation.key());
			}
		}
	}
}
