package net.davethemlgpro.client.datagen;

import net.davethemlgpro.client.translation.TranslationKey;

import java.util.Collections;
import java.util.EnumMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static java.util.Map.entry;
import static net.davethemlgpro.client.translation.TranslationKey.*;

public enum HudLanguage {
	EN(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "Open HUD Layout Editor"),
		entry(MODULE_ARMOR, "Armor HUD"),
		entry(EDITOR_TITLE, "HUD Layout Editor"),
		entry(EDITOR_INSTRUCTIONS, "Drag to move. Shift-click a HUD for quick settings."),
		entry(EDITOR_RESET, "Reset"),
		entry(EDITOR_SAVE_FAILED, "Changes could not be saved."),
		entry(POPOVER_NO_SETTINGS, "No quick settings available."),
		entry(SETTINGS_TAB_LAYOUT, "Layout"),
		entry(SETTINGS_TAB_BAR, "Bar"),
		entry(SETTINGS_TAB_TEXT, "Text"),
		entry(SETTINGS_SECTION_LAYOUT, "Layout"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Durability Bar"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Durability Text"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Low Durability Warning"),
		entry(SETTINGS_ARMOR_ORIENTATION, "Orientation"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION, "Arranges armor slots horizontally or vertically."),
		entry(SETTINGS_ARMOR_SCALE, "Scale"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Changes the size of the entire Armor HUD."),
		entry(SETTINGS_ARMOR_SPACING, "Slot Spacing"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Controls the space between armor slots."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Slot Style"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION, "Selects the background style used for armor slots."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Show Empty Slots"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION, "Shows slots even when no armor is equipped."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Center Visible Slots"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Centers equipped armor slots when empty slots are hidden."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Show Durability Bar"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Shows a durability bar for damageable armor."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Bar Height"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Controls the height of the durability bar."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Horizontal Padding"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Adds horizontal space inside the durability bar."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Text Display"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Selects whether durability is hidden, a value, or a percentage."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Text Position"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Positions the durability text relative to each armor slot."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Text Scale"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Changes the size of the durability text."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Text Shadow"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Draws a shadow behind the durability text."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Color Text by Durability"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Uses healthy, warning, and critical colors for durability text."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Show Low Durability Warning"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Highlights armor whose durability is at or below the threshold."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Warning Threshold"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Sets the durability percentage at which warnings begin."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Warning Style"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Selects how the low-durability warning is animated."),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertical"),
		entry(SETTINGS_VALUE_CLEAR, "No Background"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventory"),
		entry(SETTINGS_VALUE_HOTBAR, "Hotbar"),
		entry(SETTINGS_VALUE_NONE, "Hidden"),
		entry(SETTINGS_VALUE_VALUE, "Value"),
		entry(SETTINGS_VALUE_PERCENT, "Percentage"),
		entry(SETTINGS_VALUE_TOP, "Top"),
		entry(SETTINGS_VALUE_BOTTOM, "Bottom"),
		entry(SETTINGS_VALUE_LEFT, "Left"),
		entry(SETTINGS_VALUE_RIGHT, "Right"),
		entry(SETTINGS_VALUE_CENTER, "Center"),
		entry(SETTINGS_VALUE_COLOR, "Color"),
		entry(SETTINGS_VALUE_PULSE, "Pulse"),
		entry(SETTINGS_VALUE_FLASH, "Flash")
	), "en_us"),
	DE(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "HUD-Layout-Editor öffnen"),
		entry(MODULE_ARMOR, "Rüstungs-HUD"),
		entry(EDITOR_TITLE, "HUD-Layout-Editor"),
		entry(EDITOR_INSTRUCTIONS, "Ziehen zum Verschieben. Umschalt-Klick: Schnelleinstellungen."),
		entry(EDITOR_RESET, "Zurücksetzen"),
		entry(EDITOR_SAVE_FAILED, "Änderungen konnten nicht gespeichert werden."),
		entry(POPOVER_NO_SETTINGS, "Keine Schnelleinstellungen verfügbar."),
		entry(SETTINGS_TAB_LAYOUT, "Layout"),
		entry(SETTINGS_TAB_BAR, "Leiste"),
		entry(SETTINGS_TAB_TEXT, "Text"),
		entry(SETTINGS_SECTION_LAYOUT, "Layout"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Haltbarkeitsleiste"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Haltbarkeitstext"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Warnung bei niedriger Haltbarkeit"),
		entry(SETTINGS_ARMOR_ORIENTATION, "Ausrichtung"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION,
			"Ordnet die Rüstungsslots horizontal oder vertikal an."),
		entry(SETTINGS_ARMOR_SCALE, "Skalierung"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Ändert die Größe des gesamten Rüstungs-HUDs."),
		entry(SETTINGS_ARMOR_SPACING, "Slot-Abstand"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Legt den Abstand zwischen Rüstungsslots fest."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Slot-Stil"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION, "Legt den Hintergrundstil der Rüstungsslots fest."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Leere Slots anzeigen"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION,
			"Zeigt Slots auch an, wenn keine Rüstung ausgerüstet ist."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Sichtbare Slots zentrieren"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Zentriert ausgerüstete Rüstungsslots, wenn leere Slots ausgeblendet sind."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Haltbarkeitsleiste anzeigen"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Zeigt eine Haltbarkeitsleiste für beschädigbare Rüstung an."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Leistenhöhe"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Legt die Höhe der Haltbarkeitsleiste fest."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Horizontaler Innenabstand"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Fügt horizontalen Abstand innerhalb der Haltbarkeitsleiste hinzu."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Textanzeige"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Zeigt die Haltbarkeit ausgeblendet, als Wert oder als Prozentzahl an."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Textposition"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Positioniert den Haltbarkeitstext relativ zum Rüstungsslot."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Textskalierung"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Ändert die Größe des Haltbarkeitstextes."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Textschatten"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Zeichnet einen Schatten hinter dem Haltbarkeitstext."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Text nach Haltbarkeit färben"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Verwendet Farben für gesunde, warnende und kritische Haltbarkeit."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Warnung anzeigen"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Hebt Rüstung am oder unter dem Grenzwert hervor."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Warngrenzwert"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Legt den Haltbarkeitswert fest, ab dem gewarnt wird."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Warnstil"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Legt die Animation der Haltbarkeitswarnung fest."),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertikal"),
		entry(SETTINGS_VALUE_CLEAR, "Ohne Hintergrund"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventar"),
		entry(SETTINGS_VALUE_HOTBAR, "Schnellleiste"),
		entry(SETTINGS_VALUE_NONE, "Ausgeblendet"),
		entry(SETTINGS_VALUE_VALUE, "Wert"),
		entry(SETTINGS_VALUE_PERCENT, "Prozent"),
		entry(SETTINGS_VALUE_TOP, "Oben"),
		entry(SETTINGS_VALUE_BOTTOM, "Unten"),
		entry(SETTINGS_VALUE_LEFT, "Links"),
		entry(SETTINGS_VALUE_RIGHT, "Rechts"),
		entry(SETTINGS_VALUE_CENTER, "Mitte"),
		entry(SETTINGS_VALUE_COLOR, "Farbe"),
		entry(SETTINGS_VALUE_PULSE, "Pulsieren"),
		entry(SETTINGS_VALUE_FLASH, "Blinken")
	), "de_de", "de_at"),
	ES(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "Abrir el editor de diseños del HUD"),
		entry(MODULE_ARMOR, "HUD de armadura"),
		entry(EDITOR_TITLE, "Editor de diseño de HUD"),
		entry(EDITOR_INSTRUCTIONS, "Arrastra para mover. Mayús-clic: ajustes rápidos."),
		entry(EDITOR_RESET, "Restablecer"),
		entry(EDITOR_SAVE_FAILED, "No se han podido guardar los cambios."),
		entry(POPOVER_NO_SETTINGS, "No hay ajustes rápidos disponibles."),
		entry(SETTINGS_TAB_LAYOUT, "Diseño"),
		entry(SETTINGS_TAB_BAR, "Barra"),
		entry(SETTINGS_TAB_TEXT, "Texto"),
		entry(SETTINGS_SECTION_LAYOUT, "Diseño"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Barra de durabilidad"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Texto de durabilidad"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Aviso de poca durabilidad"),
		entry(SETTINGS_ARMOR_ORIENTATION, "Orientación"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION,
			"Organiza las ranuras de armadura horizontal o verticalmente."),
		entry(SETTINGS_ARMOR_SCALE, "Escala"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Cambia el tamaño de todo el HUD de armadura."),
		entry(SETTINGS_ARMOR_SPACING, "Espaciado de ranuras"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Controla el espacio entre las ranuras de armadura."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Estilo de ranura"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION,
			"Selecciona el estilo de fondo de las ranuras de armadura."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Mostrar ranuras vacías"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION,
			"Muestra las ranuras incluso cuando no hay armadura equipada."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Centrar ranuras visibles"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Centra las ranuras equipadas cuando las ranuras vacías están ocultas."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Mostrar barra de durabilidad"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Muestra una barra de durabilidad para la armadura que puede dañarse."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Altura de la barra"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Controla la altura de la barra de durabilidad."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Relleno horizontal"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Añade espacio horizontal dentro de la barra de durabilidad."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Visualización del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Muestra la durabilidad oculta, como valor o como porcentaje."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Posición del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Coloca el texto de durabilidad respecto a cada ranura de armadura."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Escala del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Cambia el tamaño del texto de durabilidad."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Sombra del texto"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Dibuja una sombra detrás del texto de durabilidad."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Colorear texto por durabilidad"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Usa colores saludable, de aviso y crítico para el texto."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Mostrar aviso de poca durabilidad"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Resalta la armadura cuya durabilidad está en el umbral o por debajo."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Umbral de aviso"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Establece el porcentaje de durabilidad que activa el aviso."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Estilo del aviso"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Selecciona cómo se anima el aviso de poca durabilidad."),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertical"),
		entry(SETTINGS_VALUE_CLEAR, "Sin fondo"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventario"),
		entry(SETTINGS_VALUE_HOTBAR, "Barra rápida"),
		entry(SETTINGS_VALUE_NONE, "Oculto"),
		entry(SETTINGS_VALUE_VALUE, "Valor"),
		entry(SETTINGS_VALUE_PERCENT, "Porcentaje"),
		entry(SETTINGS_VALUE_TOP, "Arriba"),
		entry(SETTINGS_VALUE_BOTTOM, "Abajo"),
		entry(SETTINGS_VALUE_LEFT, "Izquierda"),
		entry(SETTINGS_VALUE_RIGHT, "Derecha"),
		entry(SETTINGS_VALUE_CENTER, "Centro"),
		entry(SETTINGS_VALUE_COLOR, "Color"),
		entry(SETTINGS_VALUE_PULSE, "Pulso"),
		entry(SETTINGS_VALUE_FLASH, "Destello")
	), "es_mx", "es_es"),
	FR_FR(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "Ouvrir l'éditeur de mise en page HUD"),
		entry(MODULE_ARMOR, "Affichage tête haute de l'armure"),
		entry(EDITOR_TITLE, "Éditeur de mise en page HUD"),
		entry(EDITOR_INSTRUCTIONS, "Glisser pour déplacer. Maj-clic : réglages rapides."),
		entry(EDITOR_RESET, "Réinitialiser"),
		entry(EDITOR_SAVE_FAILED, "Les modifications n'ont pas pu être enregistrées."),
		entry(POPOVER_NO_SETTINGS, "Aucun réglage rapide disponible."),
		entry(SETTINGS_TAB_LAYOUT, "Disposition"),
		entry(SETTINGS_TAB_BAR, "Barre"),
		entry(SETTINGS_TAB_TEXT, "Texte"),
		entry(SETTINGS_SECTION_LAYOUT, "Disposition"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Barre de durabilité"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Texte de durabilité"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Alerte de faible durabilité"),
		entry(SETTINGS_ARMOR_ORIENTATION, "Orientation"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION,
			"Dispose les emplacements d'armure horizontalement ou verticalement."),
		entry(SETTINGS_ARMOR_SCALE, "Échelle"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Modifie la taille de tout l'affichage de l'armure."),
		entry(SETTINGS_ARMOR_SPACING, "Espacement des emplacements"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Contrôle l'espace entre les emplacements d'armure."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Style des emplacements"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION,
			"Sélectionne le style d'arrière-plan des emplacements d'armure."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Afficher les emplacements vides"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION,
			"Affiche les emplacements même lorsqu'aucune armure n'est équipée."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Centrer les emplacements visibles"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Centre les emplacements équipés lorsque les emplacements vides sont masqués."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Afficher la barre de durabilité"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Affiche une barre de durabilité pour les pièces d'armure endommageables."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Hauteur de la barre"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Contrôle la hauteur de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Marge intérieure horizontale"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Ajoute un espace horizontal à l'intérieur de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Affichage du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Masque la durabilité ou l'affiche en valeur ou en pourcentage."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Position du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Place le texte de durabilité par rapport à chaque emplacement."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Échelle du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Modifie la taille du texte de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Ombre du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Ajoute une ombre derrière le texte de durabilité."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Colorer le texte selon la durabilité"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Utilise les couleurs saine, d'alerte et critique pour le texte."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Afficher l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Met en évidence l'armure dont la durabilité atteint le seuil."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Seuil d'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Définit le pourcentage de durabilité qui déclenche l'alerte."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Style de l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Sélectionne l'animation de l'alerte de faible durabilité."),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertical"),
		entry(SETTINGS_VALUE_CLEAR, "Sans arrière-plan"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventaire"),
		entry(SETTINGS_VALUE_HOTBAR, "Barre rapide"),
		entry(SETTINGS_VALUE_NONE, "Masqué"),
		entry(SETTINGS_VALUE_VALUE, "Valeur"),
		entry(SETTINGS_VALUE_PERCENT, "Pourcentage"),
		entry(SETTINGS_VALUE_TOP, "Haut"),
		entry(SETTINGS_VALUE_BOTTOM, "Bas"),
		entry(SETTINGS_VALUE_LEFT, "Gauche"),
		entry(SETTINGS_VALUE_RIGHT, "Droite"),
		entry(SETTINGS_VALUE_CENTER, "Centre"),
		entry(SETTINGS_VALUE_COLOR, "Couleur"),
		entry(SETTINGS_VALUE_PULSE, "Pulsation"),
		entry(SETTINGS_VALUE_FLASH, "Clignotement")
	), "fr_fr"),
	FR_CA(translations(
		entry(KEY_CATEGORY_GENERAL, "Another HUD Mod"),
		entry(KEY_OPEN_LAYOUT_EDITOR, "Ouvrir l'éditeur de disposition HUD"),
		entry(MODULE_ARMOR, "Interface d'affichage de l'armure"),
		entry(EDITOR_TITLE, "Éditeur de mise en page HUD"),
		entry(EDITOR_INSTRUCTIONS, "Glisser pour déplacer. Maj-clic : réglages rapides."),
		entry(EDITOR_RESET, "Réinitialiser"),
		entry(EDITOR_SAVE_FAILED, "Les modifications n'ont pas pu être enregistrées."),
		entry(POPOVER_NO_SETTINGS, "Aucun réglage rapide disponible."),
		entry(SETTINGS_TAB_LAYOUT, "Disposition"),
		entry(SETTINGS_TAB_BAR, "Barre"),
		entry(SETTINGS_TAB_TEXT, "Texte"),
		entry(SETTINGS_SECTION_LAYOUT, "Disposition"),
		entry(SETTINGS_SECTION_DURABILITY_BAR, "Barre de durabilité"),
		entry(SETTINGS_SECTION_DURABILITY_TEXT, "Texte de durabilité"),
		entry(SETTINGS_SECTION_LOW_DURABILITY_WARNING, "Alerte de faible durabilité"),
		entry(SETTINGS_ARMOR_ORIENTATION, "Orientation"),
		entry(SETTINGS_ARMOR_ORIENTATION_DESCRIPTION,
			"Dispose les emplacements d'armure horizontalement ou verticalement."),
		entry(SETTINGS_ARMOR_SCALE, "Échelle"),
		entry(SETTINGS_ARMOR_SCALE_DESCRIPTION, "Modifie la taille de toute l'interface d'armure."),
		entry(SETTINGS_ARMOR_SPACING, "Espacement des emplacements"),
		entry(SETTINGS_ARMOR_SPACING_DESCRIPTION, "Contrôle l'espace entre les emplacements d'armure."),
		entry(SETTINGS_ARMOR_SLOT_STYLE, "Style des emplacements"),
		entry(SETTINGS_ARMOR_SLOT_STYLE_DESCRIPTION,
			"Sélectionne le style d'arrière-plan des emplacements d'armure."),
		entry(SETTINGS_ARMOR_SHOW_EMPTY, "Afficher les emplacements vides"),
		entry(SETTINGS_ARMOR_SHOW_EMPTY_DESCRIPTION,
			"Affiche les emplacements même lorsqu'aucune armure n'est équipée."),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE, "Centrer les emplacements visibles"),
		entry(SETTINGS_ARMOR_CENTER_VISIBLE_DESCRIPTION,
			"Centre les emplacements équipés lorsque les emplacements vides sont masqués."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE, "Afficher la barre de durabilité"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_VISIBLE_DESCRIPTION,
			"Affiche une barre de durabilité pour les pièces d'armure endommageables."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT, "Hauteur de la barre"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_HEIGHT_DESCRIPTION,
			"Contrôle la hauteur de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING, "Marge intérieure horizontale"),
		entry(SETTINGS_ARMOR_DURABILITY_BAR_PADDING_DESCRIPTION,
			"Ajoute un espace horizontal à l'intérieur de la barre de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_MODE, "Affichage du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_MODE_DESCRIPTION,
			"Masque la durabilité ou l'affiche en valeur ou en pourcentage."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION, "Position du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_POSITION_DESCRIPTION,
			"Place le texte de durabilité par rapport à chaque emplacement."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE, "Échelle du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SCALE_DESCRIPTION,
			"Modifie la taille du texte de durabilité."),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW, "Ombre du texte"),
		entry(SETTINGS_ARMOR_DURABILITY_TEXT_SHADOW_DESCRIPTION,
			"Ajoute une ombre derrière le texte de durabilité."),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT, "Colorer le texte selon la durabilité"),
		entry(SETTINGS_ARMOR_COLOR_BASED_DURABILITY_TEXT_DESCRIPTION,
			"Utilise les couleurs saine, d'alerte et critique pour le texte."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE, "Afficher l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_VISIBLE_DESCRIPTION,
			"Met en évidence l'armure dont la durabilité atteint le seuil."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD, "Seuil d'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_THRESHOLD_DESCRIPTION,
			"Définit le pourcentage de durabilité qui déclenche l'alerte."),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE, "Style de l'alerte"),
		entry(SETTINGS_ARMOR_LOW_DURABILITY_WARNING_STYLE_DESCRIPTION,
			"Sélectionne l'animation de l'alerte de faible durabilité."),
		entry(SETTINGS_VALUE_HORIZONTAL, "Horizontal"),
		entry(SETTINGS_VALUE_VERTICAL, "Vertical"),
		entry(SETTINGS_VALUE_CLEAR, "Sans arrière-plan"),
		entry(SETTINGS_VALUE_INVENTORY, "Inventaire"),
		entry(SETTINGS_VALUE_HOTBAR, "Barre rapide"),
		entry(SETTINGS_VALUE_NONE, "Masqué"),
		entry(SETTINGS_VALUE_VALUE, "Valeur"),
		entry(SETTINGS_VALUE_PERCENT, "Pourcentage"),
		entry(SETTINGS_VALUE_TOP, "Haut"),
		entry(SETTINGS_VALUE_BOTTOM, "Bas"),
		entry(SETTINGS_VALUE_LEFT, "Gauche"),
		entry(SETTINGS_VALUE_RIGHT, "Droite"),
		entry(SETTINGS_VALUE_CENTER, "Centre"),
		entry(SETTINGS_VALUE_COLOR, "Couleur"),
		entry(SETTINGS_VALUE_PULSE, "Pulsation"),
		entry(SETTINGS_VALUE_FLASH, "Clignotement")
	), "fr_ca");

	static {
		Set<String> locales = new HashSet<>();
		for (HudLanguage language : values()) {
			if (language.locales.isEmpty()) {
				throw new IllegalStateException(language.name() + " has no locales");
			}
			for (String locale : language.locales) {
				if (!locales.add(locale)) {
					throw new IllegalStateException("Duplicate language locale: " + locale);
				}
			}
		}
		EN.requireComplete();
	}

	private final Map<TranslationKey, String> translations;
	private final List<String> locales;

	HudLanguage(Map<TranslationKey, String> translations, String... locales) {
		this.translations = translations;
		this.locales = List.of(locales);
	}

	public List<String> getLocales() {
		return locales;
	}

	public Map<TranslationKey, String> getTranslations() {
		return translations;
	}

	@SafeVarargs
	private static Map<TranslationKey, String> translations(Map.Entry<TranslationKey, String>... entries) {
		EnumMap<TranslationKey, String> values = new EnumMap<>(TranslationKey.class);
		for (Map.Entry<TranslationKey, String> entry : entries) {
			if (values.put(entry.getKey(), entry.getValue()) != null) {
				throw new IllegalStateException("Duplicate translation: " + entry.getKey().key());
			}
		}
		return Collections.unmodifiableMap(values);
	}

	private void requireComplete() {
		for (TranslationKey translation : TranslationKey.values()) {
			if (!translations.containsKey(translation)) {
				throw new IllegalStateException(locales.getFirst() + " is missing translation " + translation.key());
			}
		}
	}
}
